feat: update for latest DashCore Instant Send
dashpay/dashcore-node pull request #96
Opened 2023-03-17 20:40 UTC by coolaj86

This is to fix insight-api deployments (such as https://insight.dash.org), which have had broken Instant Send due to RPC incompatibility since DashCore v18.

2023-03-23 00:13 UTC, strophy approved these changes, later dismissed

2023-03-23 01:42 UTC, shumkov requested changes

2023-03-23 01:42 UTC, shumkov commented on package.json
> +    "@dashevo/dashcore-lib": "^0.19.44",
Let's use last version 0.20.0?

2023-03-23 19:03 UTC, coolaj86 commented on package.json
> +    "@dashevo/dashcore-lib": "^0.19.44",
Did that come out last night? That wasn't there before.

Updating...

2023-03-23 19:12 UTC, coolaj86 commented
@shumkov Updated.

2023-03-24 02:06 UTC, shumkov approved these changes
👍

2023-03-24 02:06 UTC, merged